### ISSUE TITLE
'Sorry, something went wrong' facebook screen

### ISSUE THREAD

**Issue by joelfloressottile** [capacitor-community/facebook-login#10]
**Describe the bug**
Whenever clicking on a button that fires the facebook login function I get redirected to facebook but instead of a login screen I get a screen saying that something when wrong. 

> Sorry, something went wrong. We are working on it and we'll get it fixed as soon as we can.

I've noticed that I'm not the only encountering this issue, as someone on [this post](https://github.com/rdlabo-team/capacitor-facebook-login/issues/33) made in the old repo shows exactly the same problem I'm having, but for iOS.
I've been having this when installing the plugin from the old repo and also when installing it from here.

**To Reproduce**
Run your function where `Plugins.FacebookLogin.login()` is triggered.

**Expected behavior**
A facebook page showing login form

**Screenshots**
https://pasteboard.co/JgpRo2y.jpg

**Smartphone**
Samsung S8 SM-G950F
Android 9

**Comment by rdlabo** [comment]
Maybe you mistake configuration. Please check to https://github.com/capacitor-community/facebook-login#android-configuration , and https://developers.facebook.com/docs/facebook-login/android
This plugin is working in my environment and apps.

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.1
   @angular-devkit/schematics    : 10.0.1
   @angular/cli                  : 10.0.1
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : not installed

System:

   NodeJS : v12.16.2 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```
