### ISSUE TITLE
Android App crashes immediately after including this package

### ISSUE THREAD

**Issue by MaxWieand** [capacitor-community/facebook-login#100]
**Describe the bug**
I am developing an android app with Ionic (Angular). But as soon as I include the facebook-login (newest version), the app crashes with the following error which I got from Logcat:

> The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
>         at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
>         at com.facebook.login.LoginManager.<init>(LoginManager.java:79)
>         at com.facebook.login.LoginManager.getInstance(LoginManager.java:105)
>         at com.getcapacitor.community.facebooklogin.FacebookLogin.load(FacebookLogin.java:84)
>         at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
>         at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
>         at com.getcapacitor.Bridge.registerPlugin(Bridge.java:509)
>         at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:464)
>         at com.getcapacitor.Bridge.<init>(Bridge.java:191)
>         at com.getcapacitor.Bridge.<init>(Bridge.java:65)
>         at com.getcapacitor.Bridge$Builder.create(Bridge.java:1308)
>         at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
>         at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
>         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
>         at android.app.Activity.performStart(Activity.java:8076)
>         at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
>         at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
>         at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
>         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loopOnce(Looper.java:201)
>         at android.os.Looper.loop(Looper.java:288)
>         at android.app.ActivityThread.main(ActivityThread.java:7839)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Can anyone tell me where I need to initialize the SDK properly? 
And please, no suggestions to fix it in the generated android project (like many other people do whenever some Ionic errors appear related to android).

**Comment by MaxWieand** [comment]
Managed it.

**Comment by Rebaiahmed** [comment]
Can you share how did you manage it?

**Comment by Rebaiahmed** [comment]
Because I'm facing the same issue ..

**Comment by anonimitoraf** [comment]
@Rebaiahmed Personally, for me it was because I accidentally skipped this part:
> In file android/app/src/main/AndroidManifest.xml, add the following XML elements under <manifest><application>

from  https://github.com/capacitor-community/facebook-login#android-configuration
