### ISSUE TITLE
Problem on iOS Intel CPU: version 4.0.0 (and version 4.0.0-1) don't work on real device (Android, Xcode Simulator with Intel Cpu and ARM real devices / Simulators work fine) 

### ISSUE THREAD

**Issue by ciccilleju** [capacitor-community/facebook-login#104]
hello,
I'm developing a Ionic Capacitor 4 app. 

My computer is an iMac with monterey and Intel I7 CPU

Until this morning I was using succesfuly plugin's version 3.4.0, after the update it doesn't work anymore.
I've tried removing and reistalling the plugin again without any luck on real device (it still seems to be working on simulator)

I get this kind of error if I install it on a real device
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/42606234/186915054-4ac77072-b996-4ab2-8bdf-10550cbaf331.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/42606234/186915110-fe7cb256-b220-42b6-a7c0-ffc2f1091977.png">

Showing All Messages
Building for iOS, but linking in dylib file (/Users/francescodegiorgio/Library/Developer/Xcode/DerivedData/App-fzpdcmihaxuphrbsyzxauwqesjby/Build/Products/Debug-iphoneos/FBAEMKit.framework/FBAEMKit) built for iOS Simulator, file '/Users/francescodegiorgio/Library/Developer/Xcode/DerivedData/App-fzpdcmihaxuphrbsyzxauwqesjby/Build/Products/Debug-iphoneos/FBAEMKit.framework/FBAEMKit' for architecture arm64

this is a message I get running the simulator
<img width="547" alt="image" src="https://user-images.githubusercontent.com/42606234/186915620-f97cc831-0ea3-4bb6-bbc5-d4a0cf8ad975.png">

if i revert my plugin to version 3.4.0 it works fine again, If i do the same on my Macbook Pro with M1 cpu, works fine.

I've noticed that FBAEMKit.release.xcconfig has a different configuration in version 4.0.0-1

this is 3.4.0
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/FBAEMKit
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/FBAEMKit/XCFrameworks" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64_armv7" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64_i386_x86_64-simulator" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64_x86_64-maccatalyst" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64_armv7" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64_i386_x86_64-simulator" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64_x86_64-maccatalyst"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
OTHER_LDFLAGS = $(inherited) -framework "FBSDKCoreKit_Basics"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/FBAEMKit
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES

this is 4.0.0-1
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/FBAEMKit
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/FBAEMKit/XCFrameworks" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64_x86_64-maccatalyst" "${PODS_ROOT}/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64_x86_64-simulator" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64_x86_64-maccatalyst" "${PODS_ROOT}/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64_x86_64-simulator"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
OTHER_LDFLAGS = $(inherited) -framework "FBSDKCoreKit_Basics"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/FBAEMKit
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES

 
thank you

**Comment by ciccilleju** [comment]
@rdlabo do you have any idea if it's something related to my computer or it is a real bug?

**Comment by ciccilleju** [comment]
started a blank ionic project, tried version 4.0.0 on ios / intel cpu, nothing to do. 
It always gives me back the error: 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/42606234/189698781-bcd76d42-99ac-44b6-9561-a3f4232c10f1.png">
and all the other ones

**Comment by cresjie** [comment]
I experienced the same issue, but I was able to fix it by upgrading to Xcode 14

**Comment by ciccilleju** [comment]
Can you show me  your apo configuration?

**Comment by cresjie** [comment]
@ciccilleju nothing special was set in my config, because i upgrade my xcode, i deleted my ios folder (just to clear out all my fix attempts for this error). After the upgrade, i ran 

- pod install --update-repo
- ionic cap sync ios
- then follow the plugin's setup

are you using either xcode 11 or 12 ? I used xcode 11 before

**Comment by ciccilleju** [comment]
i'm using 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/42606234/201872196-00d325b3-7ec9-4f28-b9f5-6332309f3dba.png">

you removed the ios folder inside your application?

**Comment by ciccilleju** [comment]
nothing. I tried to remove the ios folder and started from zero but i still get error messages:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/42606234/201891690-55f9cda6-6af3-42ea-9b37-58306838dc76.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/42606234/201891736-07be598d-e24b-4874-a165-3c4dcdba100e.png">

**Comment by ciccilleju** [comment]
can you show me your build settings configuration?

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/42606234/201893997-8ab004ba-c065-40ab-ad05-d59b756814e7.png">


i think it's where i must fix something

**Comment by cresjie** [comment]
@ciccilleju 
![Capture](https://user-images.githubusercontent.com/8773060/201900400-c0a1c256-c8d9-4a51-90f7-0e65845c61b9.PNG)
Here are some other infos:

- macOS 12.6.1, Intel i7
- xcode 14.1
- "@ionic/angular": "^6.1.9"
- "@capacitor/ios": "4.3.0",
- "@capacitor-community/facebook-login": "^4.0.0",
- I also have google sign-in installed => "@codetrix-studio/capacitor-google-auth": "^3.2.0",
- after upgrading to xcode 14, i also update node, ruby, gem, cocoapods 

> -  node 14.20.1
> - npm 6.14.17
> - ruby 3.0.0
>- gem 3.2.3
>- pod 1.11.3

**Comment by ciccilleju** [comment]
i have almost the same versions (anyway, i've updated to the latest ones).
The only different flag was "build active architecture only" set to "yes",
Setting "no"  fixed the issue... it's CRAZY

**Comment by cresjie** [comment]
@ciccilleju 
if it works facebook-login@3.4 but not on v4 it might be it be framework/library conflicts. As per in your first screenshot, error first appear in Google/Firebase library. Actually, you need to match your facebook and google library. Your google framework might not have a support for arm simulator. Same issue with others as what i read before (https://developer.apple.com/forums/thread/668320) while trying to this error

**Comment by cresjie** [comment]
@ciccilleju i'm glad it helps

**Comment by ciccilleju** [comment]
> @ciccilleju i'm glad it helps

you were great!
