### ISSUE TITLE
 Option to force sign-in page ? (To change account?)

### ISSUE THREAD

**Issue by Mageek627** [capacitor-community/facebook-login#11]
Hello, is there a way to force the display of "Sign in as John Doe ?" in the facebook page as a confirmation screen before continuing ? Because right now, if any facebook user is logged in, then this user is automatically logged in my app, without giving the choice to change account. Even after calling `FacebookLogin.logout()`.

**Comment by Mageek627** [comment]
By the way, this would make the behavior closer to the Google authentication one: https://github.com/CodetrixStudio/CapacitorGoogleAuth

**Comment by rdlabo** [comment]
I can't find this method in SDK. 
Facebook Login connect to Facebook App that is installed to same device. Maybe this is not plugin issue, this is Facebook's specification. Thanks.
