### ISSUE TITLE
Cannot resolve symbol 'community'

### ISSUE THREAD

**Issue by andrewl94** [capacitor-community/facebook-login#12]
Hi!
I've followed every step set on installation of the plugin, still I get the error from the title.

![image](https://user-images.githubusercontent.com/23385661/91228380-84a97080-e6fe-11ea-995d-deb444fb22ff.png)

**Comment by rdlabo** [comment]
Hi. Please restart android studio and clean build. Thanks.

**Comment by andrewl94** [comment]
Hi!
I've done that, still the same message. I set a clean build by rebuilding on Android Studio.
Could you be more specific on the steps of setting a clean build?

**Comment by rdlabo** [comment]
Did you do `cap sync update android` ?

**Comment by andrewl94** [comment]
Sorry for the late response.
In my case, I'm building with Quasar Framwork, then i forgot to change to src-capacitor folder of the project.

**Comment by eyecatchup** [comment]
I had the same issue. Solution was to resync with gradle files: File > Sync Project with Gradle File

**Comment by panzerfausten** [comment]
@eyecatchup  this worked for me. Commenting for visibility
