### ISSUE TITLE
registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class) not necessary

### ISSUE THREAD

**Issue by co-dax** [capacitor-community/facebook-login#137]
The plugin works without 

``` Java
registerPlugin(
      com.getcapacitor.community.facebooklogin.FacebookLogin.class
    );
```

from the following piece of code
```Java
import android.os.Bundle; // required for onCreate parameter

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    registerPlugin(
      com.getcapacitor.community.facebooklogin.FacebookLogin.class
    );
  }
}
```

...which is reported as required for the plugin to work at the following link [https://github.com/capacitor-community/facebook-login#android-configuration](https://github.com/capacitor-community/facebook-login#android-configuration)

Am I missing something?

Thanks.

**Comment by juanico18** [comment]
I have the same question. Anyone knows if is it required or not?

**Comment by rdlabo** [comment]
Thanks report. This is unnecessary from v4.
I removed from readme: https://github.com/capacitor-community/facebook-login/commit/817a16f66c63c48bed7a4f8d6cd06a67e31e693d

**Comment by co-dax** [comment]
Thanks @rdlabo!
