### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FBSDKAccessToken/FBSDKLoginManager

### ISSUE THREAD

**Issue by JovanShandro** [capacitor-community/facebook-login#16]
Bug in IOS version or am I missing something.

**Describe the bug**
I followed all the steps to use the plugin and it worked fine for android.
However for IOS I got the error shown in the screenshot below .
I also took the steps I could find in the provided link in the readme for facebook login guide in ios just before the bundle id part. 
I set up your development environment using Cocoapods, and then tried again but get the same error.

**To Reproduce**
1. Create an ionic capacitor project
2. Run 'yarn build' and 'npx cap add ios'
3. Do all necessary configurations for the plugin to work for ios
4. pod 'FBSDKLoginKit' in the Podfile and then run pod install
5.Run npx cap sync ios
6. Run project in xcode

**Expected behavior**
I expect the build to finish and an emulator to be opened

**Screenshots**
![error](https://user-images.githubusercontent.com/48320914/94520075-f14aea00-022b-11eb-99e1-dbee6bc1e904.png)

**Desktop (please complete the following information):**
 - OS: MacOs Mojave version 10.14.4 VM in Ubuntu 19.10
 - Browser firefox
 - Version 81.0

Thank you.

**Comment by rdlabo** [comment]
I added demo project: https://github.com/capacitor-community/facebook-login/tree/master/demo/angular
Please check this.

**Comment by eryzerz** [comment]
I got same problem, already did npx cap update and sync

**Comment by rdlabo** [comment]
>  Clean build then build again

Maybe this is solution in this issue. Thanks comment! @eryzerz

**Comment by JovanShandro** [comment]
Thank @eryzerz. Clean build and building again also fixed it for me.

**Comment by loburets** [comment]
If anyone wondering how to clean the build:
![image](https://user-images.githubusercontent.com/5417461/114308252-ff47c480-9b04-11eb-9961-af2a72674bde.png)

**Comment by tekpokhrel** [comment]
Yes. Clean Build Folder worked for me too! Thanks

**Comment by stefanhk31** [comment]
This is occurring for me, and clean/build doesn't fix it. 

Xcode 12.5.1
Capacitor/core 2.4.7
Capacitor/cli 2.4.4
FB login plugin 1.0.3
