### ISSUE TITLE
Unable to get Facebook profile photo anymore

### ISSUE THREAD

**Issue by dodomui** [capacitor-community/facebook-login#17]
**Describe the bug**
Hi, I' having issue to get facebook user profile photo recently, it was working just fine previously.
Any idea what is the issue?

**To Reproduce**
1. Authenticate a new facebook user
2. And it return only the blank facebook user profile image.

**Expected behavior**
Expected to received user profile photo as previously.

**Screenshots**
[https://scontent.fkul17-1.fna.fbcdn.net/v/t1.30497-1/cp0/c15.0.50.50a/p50x50/84628273_176159830277856_972693363922829312_n.jpg?_nc_cat=1&_nc_sid=12b3be&_nc_ohc=avjs1eN81qIAX8LLQ-r&_nc_ht=scontent.fkul17-1.fna&_nc_tp=27&oh=7bc5a81b88f6a922b745b3c87f29808d&oe=5FA4D0B8](url)

**Additional context**
Ionic:

   Ionic CLI                     : 6.11.11 (/Users/.../.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1001.4
   @angular-devkit/schematics    : 10.1.4
   @angular/cli                  : 10.1.4
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.1

System:

   NodeJS : v12.16.1 (/Users/.../.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

**Comment by rdlabo** [comment]
This is not plugin issue. It is a specification of Facebook.
