### ISSUE TITLE
FB Sdk versions supported by android and IOS

### ISSUE THREAD

**Issue by AlvinTCH** [capacitor-community/facebook-login#22]
Hi. First of all, thanks for developing this as it has helped me a lot for my project. Getting into the issue directly, I have noticed in my facebook developer account that the android SDK is outdated. Just want to ask what are the SDK versions supported by this plugin? am I able to update the SDK versions as stated under the facebook developers like this?

For android
`implementation 'com.facebook.android:facebook-android-sdk:8.1.0'`

and pod update for ios?

**Comment by ciccilleju** [comment]
I got the following email from Facebook for Developers

_Required action: You must update the version of the Facebook SDK currently in use for your applications. As part of our SDK version 9.0 release, we are requiring developers to upgrade to our latest version. This update will offer developers new security features, increased resiliency, and improved performance.

Your current SDK is out of date and will no longer be supported by Facebook. We will continue to allow API calls from your SDK for a two-year transition period. Starting January 19, 2023, we will block all calls from outdated SDKs. We encourage you to upgrade to version 9.0 as soon as possible to avoid disruption of your application and access all the benefits of our new SDK._

What should we do to update to the latest version or at least to a supported one?

thanks

**Comment by rdlabo** [comment]
Thanks for issues. I will update android library version.

And 

> _Required action: You must update the version of the Facebook SDK currently in use for your applications.

Pods use newest library version:

- https://github.com/capacitor-community/facebook-login/blob/master/CapacitorCommunityFacebookLogin.podspec
- https://cocoapods.org/pods/FacebookLogin

So I will wait for the CocoaPods update. Thanks.

**Comment by rdlabo** [comment]
https://github.com/capacitor-community/facebook-login/releases/tag/v1.1.0

**Comment by aMUSiC** [comment]
The FacebookLogin pod has been retired on November 2019. There is a new pod that should be used to get the latest FacebookLogin and FacebookCore. You can see the migration guide here:

https://github.com/facebookarchive/facebook-swift-sdk/blob/master/MigrationGuide.md

From what I read, it's only a matter of changing the pod names and the method names, while everything else remains the same.

and here's the new pod

https://cocoapods.org/pods/FBSDKLoginKit
