### ISSUE TITLE
Android "FB is not defined"

### ISSUE THREAD

**Issue by yukikwi** [capacitor-community/facebook-login#31]
**Describe the bug**
RemoteJS return FB is not defined on complied app running on android. I follow read me guide for android (with out MainActivity step because capacitor3 didn't need it)

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 10
 - OS: Android 11
 - Capacitor 3
 - Plugin Version 1.1.0

**Comment by rdlabo** [comment]
This plugin don't support Capacitor3 yet.

**Comment by rdlabo** [comment]
@yukikwi  I start to development support v3: https://github.com/capacitor-community/facebook-login/pull/32
Please check this thread. Thanks.
