### ISSUE TITLE
Update FB SDKs to the latest versions (9)

### ISSUE THREAD

**Issue by aMUSiC** [capacitor-community/facebook-login#34]
**Is your feature request related to a problem? Please describe.**
The plugin currently uses old and deprecated/retired versions of the Facebook SDK for both iOS and Android. They are on version 5, while version 9 is out and Facebook is strongly urging to update to this one. Usage of version 5 creates compatibility issues with other plugins and SDKs that require later versions of FacebookCore, and additionally cannot take advantage of the iOS 14 changes related to tracking and data collection.

**Describe the solution you'd like**
Update Facebook dependencies to the latest versions, and change the Class/Method names to reflect the names in the new SDK.
For Android the maven dependency is com.facebook.android:facebook-login:8.1.0
For iOS the pod dependency is https://cocoapods.org/pods/FBSDKLoginKit

The migration guide for iOS can be found here: https://github.com/facebookarchive/facebook-swift-sdk/blob/master/MigrationGuide.md

**Describe alternatives you've considered**
I haven't considered any alternatives yet.

**Comment by rdlabo** [comment]
Thanks issue.
I updated, but this has break changes. So label as v2.0.0:
https://github.com/capacitor-community/facebook-login/commit/4168982acf8454e3ac9ef7c51f5d68f46801422c

Please try this. Thanks.

**Comment by aMUSiC** [comment]
I am not using FB sharing, so I can't test for the additional parameters needed, but everything else works fine. Thank you for the quick update.
