### ISSUE TITLE
CocoaPods could not find compatible versions for pod FBSDKCoreKit

### ISSUE THREAD

**Issue by AlvinTCH** [capacitor-community/facebook-login#35]
Hi, I recently updated the version of this package on my app to v2 and when I tried to build the app, it says:

`
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    CapacitorCommunityFacebookLogin (from `../../node_modules/@capacitor-community/facebook-login`) was resolved to 1.1.0, which depends on
      FBSDKCoreKit (= 9.0.1)

    FBSDKCoreKit

Specs satisfying the FBSDKCoreKit, FBSDKCoreKit (= 9.0.1) dependency were found, but they required a higher minimum deployment target
`
I have updated the appDelegate.swift file according to the documentation. Did I miss out anything?

**Comment by rdlabo** [comment]
What's your minimum deployment target??
Please check demo: https://github.com/capacitor-community/facebook-login/tree/master/demo/angular

Thanks.

**Comment by AlvinTCH** [comment]
Hi,
I believe it's 11, which is the standard version for capacitor. How do I update the minimum deployment targets on capacitor? Have changed the first line in PodFile to 13 and all "IPHONEOS_DEPLOYMENT_TARGET" to 13 inside the "project.pbxproj" file

**Comment by AlvinTCH** [comment]
Did a "pod install --repo-update" where the Podfile is and it worked. Putting it here in case it helps anyone.

Thanks

**Comment by cristianlabadie** [comment]
Im having the same error,

[capacitor] [error] Analyzing dependencies
[capacitor] [!] CocoaPods could not find compatible versions for pod "CapacitorCommunityFacebookLogin":
[capacitor]   In Podfile:
[capacitor]     CapacitorCommunityFacebookLogin (from `../../node_modules/@capacitor-community/facebook-login`)
[capacitor]
[capacitor] Specs satisfying the `CapacitorCommunityFacebookLogin (from `../../node_modules/@capacitor-community/facebook-login`)` dependency were found, but they required a higher minimum deployment target.

**Comment by loburets** [comment]
Updated ios/App/Podfile to
```
platform :ios, '12.0'
```
Then `pod install --repo-update`
And it worked for me, thank you @AlvinTCH 

But later I've realised that
1) It returns back after `npx capy sync` or usual `pod install`
2) I just use capacitor 2 and the last version of this FB login plugin isn't compatible with it
So, I've just used version `"@capacitor-community/facebook-login": "2.0.0"` and it seems working

**Comment by sunitha1210** [comment]
I am trying to install community facebook plugin and facebook connect.then i am getting this error,

**Comment by itsalb3rt** [comment]
> Did a "pod install --repo-update" where the Podfile is and it worked. Putting it here in case it helps anyone.
> 
> Thanks

Still working here with Quasar v2 project with Capacitor 5
