### ISSUE TITLE
podspec file is not included in next version ('3.0.0-1')

### ISSUE THREAD

**Issue by leo6104** [capacitor-community/facebook-login#38]
**Describe the bug**
Thank you for preparing capacitor v3 :) 

I tested it with `npm i @capacitor-community/facebook-login@next` and found this problem in iOS. 

![image](https://user-images.githubusercontent.com/7777929/109190016-fe1e3a80-77d7-11eb-9d03-025c386b3ad6.png)

<img src="https://user-images.githubusercontent.com/7777929/109189990-f9598680-77d7-11eb-8bf9-4f0bf44b9ae9.png" width="320">

Can you include `CapacitorCommunityFacebookLogin.podspec` file in npm package?

**Expected behavior**
Include podspec file.

**Comment by rdlabo** [comment]
Thanks issue. I fixed this in v3.0.0-3.
Please test this.

**Comment by leo6104** [comment]
It fixed! :)

Thanks @rdlabo  👍
