### ISSUE TITLE
Facebook doesn't support anymore htpp but https only. 

### ISSUE THREAD

**Issue by mistersouls** [capacitor-community/facebook-login#41]
I tried to Facebook login with my browser and it raises **the method FB.login can no longer be called from http pages.**

I think it is no longer possible to test Facebook login in development test like http://localhost because I created an app  and users test but I was not able to disable _enforce https_ .

Thanks

**Comment by rdlabo** [comment]
Facebook require https default:
https://stackoverflow.com/questions/49400199/does-facebook-sdk-require-https

Are you angular user?? you can use `ssl` flag. Thanks.
