### ISSUE TITLE
Migration to v3 doc.

### ISSUE THREAD

**Issue by vovikdrg** [capacitor-community/facebook-login#47]
**Describe the bug**
AppDelegate.swift:3:8: error: no such module 'FacebookCore'

**To Reproduce**
I did migrated from old version to 3 and was not able to compile my app

**Expected behavior**
Maybe it make sense to add into docs information that during upgrade to make sure that we import 
`import FBSDKCoreKit`
Instead of
`import FacebookCore`

**Comment by vovikdrg** [comment]
@rdlabo I was thinking to add new section in readme with just one note. Are you fine with that?

**Comment by rdlabo** [comment]
@vovikdrg I'm sorry I overlooked this reply.
I created file https://github.com/capacitor-community/facebook-login/blob/master/BREAKING.md , so please add v3 braking change section. 
Thanks.

**Comment by vovikdrg** [comment]
@rdlabo  thanks will do :)

**Comment by rdlabo** [comment]
This may not has any update, so will close. If be update, please re-open.
Thanks.
