### ISSUE TITLE
I can't login anymore, I get the "logging into facebook from an embedded browser is disabled" error

### ISSUE THREAD

**Issue by ciccilleju** [capacitor-community/facebook-login#54]
Android 11 - Capacitor 2 version plugin, Samsung Galaxy s21 when i try to login I get the following error:

![image](https://user-images.githubusercontent.com/42606234/122602365-fd553100-d072-11eb-89e3-bd796374431f.png)

what is happening?

I worked like a charm until 2-3 days ago and on my Samsung Galaxy s9 and iPad  (newest version) it still works fine.

thank you

**Comment by loburets** [comment]
Has the same issue, fixed by using 2.0.0 version of the plugin instead of 1.x (3.x seems not compatible with capacitor 2 which I sue)
