### ISSUE TITLE
Use of unresolved identifier 'ApplicationDelegateProxy'

### ISSUE THREAD

**Issue by selcukbeyhan** [capacitor-community/facebook-login#56]
Hello,

when I use the following line as described in the README:
return ApplicationDelegateProxy.shared.application(app, open: url, options: options)

My XCode returns an error:
Use of unresolved identifier 'ApplicationDelegateProxy'

I have XCode Version 11.6 (11E708)

Is it normal?

Thanks.

**Comment by rdlabo** [comment]
Please check demo: https://github.com/capacitor-community/facebook-login/tree/master/demo/angular
I confirm this work well.

And Xcode may be old. I use v12.
Thanks.
