### ISSUE TITLE
Use latest Facebook SDK

### ISSUE THREAD

**Issue by selcukbeyhan** [capacitor-community/facebook-login#57]
Hello,

I realised, the current POD file has a version restriction for Facebook SDK:
pod 'FBSDKCoreKit', '8.2.0'
pod 'FBSDKLoginKit', '8.2.0'

However, the latest available version of the SDK is 11.0.1:
https://github.com/facebook/facebook-ios-sdk?fbclid=IwAR3rgks-zcieYDI2AW5RTDVhKGHQc-O8QtagVDGFnQlZmFKahx_pTwi5-9g

Could you please help to upgrade it?

Thank you.
Selcuk.

**Comment by rdlabo** [comment]
Thanks for issues.
I released https://github.com/capacitor-community/facebook-login/releases/tag/v3.1.0 . This update sdk version to 11.
Thanks.
