### ISSUE TITLE
Difference with cordova-plugin-facebook-connect

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/facebook-login#60]
Not an issue but a question.
I'm using [cordova-plugin-facebook-connect](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect) to capture events and was wondering if I can replace it with this one since I'm converting to capacitor wherever possible.

Thanks

**Comment by rdlabo** [comment]
It may be possible to replace. But you may not be able to use both plugins at same time.

**Comment by jongbonga** [comment]
Hi 

thanks for the reply.

Yes can’t use both at the same time.
What I need to know is the steps to enable the autologevents and the ability to do so on iOS14+.

**Comment by arturomf** [comment]
Hi!

I'm interested in knowing how to enable autologevents after getting user consent. With iOS14+ it's a must

Thanks!

**Comment by rdlabo** [comment]
@arturomf This is `Login Plugin` . So now can't use log event.
Thanks.
