### ISSUE TITLE
issue after work on phone.

### ISSUE THREAD

**Issue by whitersun** [capacitor-community/facebook-login#66]
**Describe the bug**

**Description**
After using android studio build Debug and APK app. I got success app-debug.apk. But the problem I was installed into my phone and unable open the app. 
System always calling for "Unfortunately <App name> has stopped."

**To Reproduce**
1. After build apk from android studio and follow the step was on readme tutorial taught.
2. Download to mobile phone and install.
3. After click the app, app open and got black screen. Pass Through not enough 1 mins, app automatic exits
4. See error system calling "Unfortunately <App name> has stopped."

**Expected behavior**
App should correctly open and working well.

**Screenshots**

![340602](https://user-images.githubusercontent.com/37898596/132557450-d9c04e74-27ef-4a70-bae2-de42d64a9b51.jpg)

**Framework**
 - Ionic vue3
 - Capacitor Platform

**Smartphone (please complete the following information):**
 - Device: Galaxy Samsung Prime 7
 - OS: Android
 - Browser none
 - Version none

**Additional context**

**Comment by rdlabo** [comment]
Please check Logs in Android. I'm suspicious about string.xml, but I can't understand it with this information.

**Comment by whitersun** [comment]
Hello @rdlabo, I am very thrilled when someone replies to my post issue.
Actually, my android studio has a little bit problem with virtual emulator devices working, so that is why I decided to build apk and installed it into my phone then make a double-check.

And that is the reason I don't get which issue make the app be stopped when I clicked to open. I used to install other capacitor plugins and get nothing issue until using @capacitor-community/facebook-login.

Here is my Github just only install @capacitor-community/facebook-login with setting a little bit to android. Please help me make a check.
[](https://github.com/whitersun/devLogin)

I wanna use Cordova from ionic native provide for developers using. But our project is using a capacitor, so I can't using Cordova plugins of the Facebook cause of some settings by type terminal...

By the way, please help me.

**Comment by rdlabo** [comment]
> Here is my Github

@whitersun maybe you forgot write repository url, didn't you?

**Comment by whitersun** [comment]
@rdlabo OMG, Pardon me. I forgot it, thanks for reminding me.
this is my Github repository URL: [](https://github.com/whitersun/devLogin)

**Comment by rdlabo** [comment]
I understood. Please check this:  The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

**Comment by whitersun** [comment]
Hello @rdlabo, it worked. I thought put inside under **<manifest>** and below **<application>**

@rdlabo Thank you so much. 　本土に、ありがとうございます
