### ISSUE TITLE
Android configuration

### ISSUE THREAD

**Issue by sbellver** [capacitor-community/facebook-login#67]
**Describe the bug**
When I change MainActivity class gives an error

**To Reproduce**
Change MainActivity.java and add/override:

```
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class);
    }
}
```

Then, when I do nix cap open android:

```
error: cannot find symbol
    public void onCreate(Bundle savedInstanceState) {
                         ^
  symbol:   class Bundle
```

 - OS:Android

**Comment by sbellver** [comment]
Maybe the README needs an update:

```
import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.community.facebooklogin.FacebookLogin;

public class MainActivity extends BridgeActivity {
  @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class);
    }
}
```

First, we need to import add import android.os.Bundle; not sure if import com.getcapacitor.community.facebooklogin.FacebookLogin; is mandatory

**Comment by Sh1n1x** [comment]
android.os.Bundle is required for onCreate parameter so is mandatory.

**Comment by Sh1n1x** [comment]
> Maybe the README needs an update:
> 
> ```
> import android.os.Bundle;
> import com.getcapacitor.BridgeActivity;
> import com.getcapacitor.community.facebooklogin.FacebookLogin;
> 
> public class MainActivity extends BridgeActivity {
>   @Override
>     public void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class);
>     }
> }
> ```
> 
> First, we need to import add import android.os.Bundle; not sure if import com.getcapacitor.community.facebooklogin.FacebookLogin; is mandatory

With your code Android app stop running when the error code:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: MY.APPLICATION, PID: 9428
    The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
```

**Comment by stewones** [comment]
Capacitor 3 should handle those imports automatically

**Comment by markterrill** [comment]
Same problem. Same fix, ie add import android.os.bundle.
npx cap sync didn't magically fix it either. Looks to be a straight up vanilla header requirement for that file.

**Comment by Caperious** [comment]
Is this step needed? Like @stewones said, Capacitor 3 should handle this imports automatically https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading
