### ISSUE TITLE
Facebook has detected [Project Name] isn't using a secure connection to transfer information. 

### ISSUE THREAD

**Issue by fjrslt** [capacitor-community/facebook-login#69]
I'm using this plugin to be able to login with Facebook using my mobile app. However, after upgrading to version 3 of Ionic Capacitor, the plugin stopped working on my Android device. 

Steps done:
1. Created App from Facebook Developers page.
2. Added App ID to Strings.xml
3. Added meta-data values to Android Manifest 
4. Imported the "com.getcapacitor.community.facebooklogin.FacebookLogin" package to MainActivity.java even though it's not required. Just to make sure that I've tried everything. 

What could possibly go wrong? Are there things I may have missed?

**Comment by Afnan0711** [comment]
Did you find any solution?

**Comment by rdlabo** [comment]
This looks android studio issue. Please reboot. Thanks.

**Comment by fjrslt** [comment]
Done that a couple of times already and still no luck. I've looked for some resources and come up with the conclusion that this plugin doesn't work with Capacitor 3 yet. Also, shouldn't you also be confirming first if the issue is resolved after sending your suggested fix?
