### ISSUE TITLE
package com.getcapacitor.community.facebooklogin does not exist

### ISSUE THREAD

**Issue by ikishanoza** [capacitor-community/facebook-login#7]
I have installed the plugin in fresh repo and when I run the project in android studio its giving me this error please see attached screenshot for more information.

![Screenshot 2020-06-29 at 11 36 43 PM](https://user-images.githubusercontent.com/18045135/86040421-a5887900-ba61-11ea-8aec-94ace6ff8634.png)

**Comment by rdlabo** [comment]
Please restart Android Studio, or clean build.
Capacitor plugin require to read in Android Project. Thanks.

![スクリーンショット 2020-07-03 16 20 58](https://user-images.githubusercontent.com/9690024/86442747-35bc0c00-bd49-11ea-81ae-29609fbe519b.png)

**Comment by piotrzuzak** [comment]
@ikishanoza ikishanoza, please do not use direct import in add method. 
It is better to use imports as follows:

`import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;
import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;
import com.getcapacitor.community.facebooklogin.FacebookLogin;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
	  add(GoogleAuth.class);
	  add(FacebookLogin.class);
    }});
  }
}`

**Comment by ikishanoza** [comment]
Ok let me try.

**Comment by ikishanoza** [comment]
still same @rdlabo @piotrzuzak 

![Screenshot 2020-07-04 at 3 07 57 PM](https://user-images.githubusercontent.com/18045135/86509793-28b22200-be08-11ea-9b25-7aa7cbb42a7d.png)

**Comment by piotrzuzak** [comment]
it should works with my imports too.
When you are adding plugin, always use npx cap sync <given_platform>

**Comment by ikishanoza** [comment]
Yeah I have done both the changes buddy thank to you to @piotrzuzak  :)

**Comment by piotrzuzak** [comment]
good to see it works, have a nice day

**Comment by jofftiquez** [comment]
Hi I am also facing this issue but I am using Quasar. Details [here](https://stackoverflow.com/questions/67123910/error-package-com-getcapacitor-community-facebooklogin-does-not-exist-error-in). None of the suggestions above worked for me. Thank you.

**Comment by qamar2** [comment]
Still this command does not work in a multi app NX monorepo: 

`npx cap update android`

Any suggestion?
