### ISSUE TITLE
Popup Blocked on Safari Iphone PWA

### ISSUE THREAD

**Issue by shprink** [capacitor-community/facebook-login#70]
**Describe the bug**

Hello, I used this cordova plugin before https://github.com/jeduan/cordova-plugin-facebook4 and switched to your's instead with capacitor v3. 

Since I release the app, users on iOS or using safari desktop run into the "popup blocked" problem that is explained here: https://www.idownloadblog.com/2021/03/30/how-to-allow-pop-ups-in-safari/

The problem is that `FacebookLogin.login` gets stuck and never respond in the case popups are blocked (default setting).

How to handle this case? Is there a way to check if safari is setup correctly to allow FB login ?

thanks

**To Reproduce**
1. Open safari on iphone or desktop with popups blocked
2. try to login

**Expected behavior**

Get an Error to let the developers know that something got wrong and it is because of safari's setting.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs at least
 - Browser: safari

**Smartphone (please complete the following information):**
 - Device: iphone XS
 - OS: latest
 - Browse safari

**Comment by ngochiep30051998** [comment]
I'm having the same problem.

**Comment by rdlabo** [comment]
Sorry, I don't know. This plugin is only wrapper: https://github.com/capacitor-community/facebook-login/blob/master/src/web.ts#L60-L80

Please check Facebook SDK. Thanks.

**Comment by WilliamFischer** [comment]
Why is this closed? The issue persists and is directly caused by this plugins implementation of the Facebook SDK.

@rdlabo Why not update the 'facebook SDK wrapper' code to use callbacks as suggested by @shprink, allowing this plugin to work in Safari on mobile?
