### ISSUE TITLE
getProfile getting Invariant Violation: Minified invariant #47458; %s Params: %s error

### ISSUE THREAD

**Issue by viktorsheep** [capacitor-community/facebook-login#73]
**Describe the bug**
Hello guys,
Function getProfile was working fine thoe time, even yesterday until now. When I try to login to facebook I get `Invariant Violation: Minified invariant #47458; %s Params: %s` when I didn't change any code related to login functions.

**To Reproduce**
1. Call login function
2. Call getProfile function

**Expected behavior**
Should return user's name, email, age_range, picture, etc.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave
 - Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additions**
My stack is : 
FrontEnd : Nuxt Vue + Cordova 
BackEnd : PHP + Laravel Lumen
Server : Ubuntu 20.04 Apache

**Comment by rdlabo** [comment]
> FrontEnd : Nuxt Vue + Cordova

This plugin is be for Capacitor. Don't work on Cordova.
