### ISSUE TITLE
Request: add Compatibility and Facebook SDK / Graph-API versions to Readme

### ISSUE THREAD

**Issue by arielhasidim** [capacitor-community/facebook-login#76]
Facebook tends to update and deprecate versions quite frequently and this dependency with Facebook is not always so easy anyway, so I think adding this to the readme file would help a lot.

See for example Cordova's [jeduan/cordova-plugin-facebook4](https://github.com/jeduan/cordova-plugin-facebook4#facebook-sdk)

**Comment by rdlabo** [comment]
Thanks for issue. added!

**Comment by arielhasidim** [comment]
> Thanks for issue. added!

Much appreciated ♥️
