### ISSUE TITLE
Does this library makes use of code_verifier and code_challenger?

### ISSUE THREAD

**Issue by bartboersma** [capacitor-community/facebook-login#8]
Hi people who made this library,

First of all, awesome library! 

I have successfully implemented Facebook login on Android and iOS using your library. While I was debugging your library, I couldn't find if a code_verifier and code_challenger is used in order to prevent malicious app's using your code (PKCE). I have implemented Google Login myself by following [this](https://developers.google.com/identity/protocols/oauth2/native-app) guide where they explain using the code_verifier and code_challenger. So I was wondering does this library use PKCE by using a code_verifier and code_challenger?

Regards,

Bart

**Comment by rdlabo** [comment]
Hi.
This plugin use Facebook Login Manager Plugin, and code_verifier and code_challenger may be in this. (I can't find how to use in outside of Login Manager)

https://github.com/facebook/facebook-ios-sdk
https://github.com/facebook/facebook-android-sdk

Thanks.

**Comment by bartboersma** [comment]
Thank you for your response
