### ISSUE TITLE
Update documentation to information what import in gradle are needed

### ISSUE THREAD

**Issue by piotrzuzak** [capacitor-community/facebook-login#9]
Hi, 

I've used your library since one year. Few days ago I've updated project to official capacitor however it was no information about new version of facebook sdk in dependencies. 

It is worth to mention for other developers that we should take care of facebook android sdk in android/app/build.gradle.

Latest one is implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
My eariler was implementation 'com.facebook.android:facebook-android-sdk:4.41.0' and it caused issue during compilation in android studio.

Please update documention if possible.

Thank you,
Piotr

**Comment by rdlabo** [comment]
Sorry for slow response.

> we should take care of facebook android sdk in android/app/build.gradle.

Don't need. You should restart Android Studio and clean build. (And waiting install). 
I added this to readme. Thanks.
https://github.com/capacitor-community/facebook-login/commit/7b0d299352a4903951089863e0e6efcfb07ec132
